version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: socialdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma-migrate:
    build: ./database
    container_name: prisma-migrate
    depends_on:
      - postgres
    env_file:
      - ./database/.env
    command: npx prisma migrate deploy
    restart: "no"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    depends_on:
      - prisma-migrate
    restart: unless-stopped

  like-service:
    build: ./like-service
    container_name: like-service
    ports:
      - "3002:3002"
    env_file:
      - ./like-service/.env
    depends_on:
      - prisma-migrate
    restart: unless-stopped

  post-service:
    build: ./post-service
    container_name: post-service
    ports:
      - "3003:3003"
    env_file:
      - ./post-service/.env
    depends_on:
      - prisma-migrate
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3004:3004"
    env_file:
      - ./user-service/.env
    depends_on:
      - prisma-migrate
    restart: unless-stopped

volumes:
  postgres_data:
